import fs from 'fs';
import path from 'path';

export interface DatabaseSchema {
  academicYears: any[];
  classes: any[];
  subjects: any[];
  teachers: any[];
  students: any[];
  grades: any[];
  attendance: any[];
  homeworks: any[];
  submissions: any[];
  announcements: any[];
  reportCards: any[];
  teacherNotes: any[];
  auditLogs: any[];
  schedules: any[];
  schoolConfig: any;
  users: any[];
}

const DB_FILE = path.join(process.cwd(), 'data_storage.json');

const INITIAL_DB: DatabaseSchema = {
  academicYears: [
    {
      id: 'ay1',
      name: 'سال تحصیلی ۱۴۰۴–۱۴۰۵',
      start_date: '1404/07/01',
      end_date: '1405/03/31',
      is_current: true,
      is_archived: false,
    },
    {
      id: 'ay2',
      name: 'سال تحصیلی ۱۴۰۳–۱۴۰۴',
      start_date: '1403/07/01',
      end_date: '1404/03/31',
      is_current: false,
      is_archived: true,
    },
  ],
  schoolConfig: {
    schoolName: 'دبیرستان دوره اول پدیده دانش',
    managerName: 'دکتر محمد رضایی',
    district: 'منطقه ۳',
    province: 'تهران',
    academicYear: '۱۴۰۴–۱۴۰۵',
    phone: '۰۲۱-۸۸۷۷۶۶۵۵',
    address: 'تهران، خیابان ولیعصر، بالاتر از میدان ونک، بن‌بست دانش، پلاک ۱۲',
    passGrade: 10,
    logoUrl: '',
    motto: 'پرورش تفکر نقادانه، خلاقیت علمی و اخلاق‌مداری',
    email: 'info@padideh.sch.ir',
    website: 'https://padideh.sch.ir',
    attendanceThreshold: 3,
  },
  classes: [
    {
      id: 'c1',
      name: 'دهم ۱ (تجربی الف)',
      grade_level: 'tenth',
      academic_year_id: 'ay1',
      room_number: '۱۰۱',
      capacity: 30,
      field_of_study: 'علوم تجربی',
      homeroom_teacher_id: 't1',
    },
    {
      id: 'c2',
      name: 'دهم ۲ (تجربی ب)',
      grade_level: 'tenth',
      academic_year_id: 'ay1',
      room_number: '۱۰۲',
      capacity: 28,
      field_of_study: 'علوم تجربی',
      homeroom_teacher_id: 't2',
    },
    {
      id: 'c3',
      name: 'دوازدهم ریاضی',
      grade_level: 'twelfth',
      academic_year_id: 'ay1',
      room_number: '۲۰۱',
      capacity: 25,
      field_of_study: 'ریاضی و فیزیک',
      homeroom_teacher_id: 't1',
    },
    {
      id: 'c4',
      name: 'یازدهم انسانی',
      grade_level: 'eleventh',
      academic_year_id: 'ay1',
      room_number: '۲۰۳',
      capacity: 24,
      field_of_study: 'ادبیات و علوم انسانی',
      homeroom_teacher_id: 't4',
    },
  ],
  subjects: [
    { id: 's1', title: 'ریاضی ۱', code: 'MATH101', coefficient: 4, grade_level: 'tenth', description: 'مجموعه‌ها، توان و ریشه، توان‌های گویا' },
    { id: 's2', title: 'هندسه ۱', code: 'GEO101', coefficient: 2, grade_level: 'tenth', description: 'ترسیم‌های هندسی و استدلال، قضیه تالس' },
    { id: 's3', title: 'فیزیک ۱', code: 'PHYS101', coefficient: 3, grade_level: 'tenth', description: 'اندازه‌گیری، کار و انرژی، ویژگی‌های فیزیکی مواد' },
    { id: 's4', title: 'شیمی ۱', code: 'CHEM101', coefficient: 3, grade_level: 'tenth', description: 'کیهان زادگاه الفبای هستی، ردپای گازها' },
    { id: 's5', title: 'فارسی و نگارش ۱', code: 'LIT101', coefficient: 4, grade_level: 'tenth', description: 'ادبیات غنایی، حماسی، تعلیمی و نگارش تحلیلی' },
    { id: 's6', title: 'دین و زندگی ۱', code: 'REL101', coefficient: 2, grade_level: 'tenth', description: 'هدف زندگی، هدایت الهی، فرجام کار' },
    { id: 's7', title: 'زبان انگلیسی ۱', code: 'ENG101', coefficient: 2, grade_level: 'tenth', description: 'Reading, Grammar, Vocabulary & Conversation' },
    { id: 's8', title: 'حسابان ۲', code: 'CALC120', coefficient: 4, grade_level: 'twelfth', description: 'تابع، مثلثات، حد و پیوستگی، مشتق' },
  ],
  teachers: [
    {
      id: 't1',
      user_id: 'u2',
      personnel_code: 'T-98102',
      national_id: '2222222222',
      username: '2222222222',
      first_name: 'دکتر احمد',
      last_name: 'حسینی',
      specialty: 'ریاضیات و هندسه تحلیلی',
      degree: 'دکتری ریاضیات کاربردی',
      phone: '09122222222',
      email: 'dr.hosseini@padideh.sch.ir',
      bio: 'استاد دانشگاه و دبیر باسابقه المپیاد ریاضی با بیش از ۱۸ سال سابقه آموزش و مؤلف کتب کمک‌آموزشی ریاضی و هندسه.',
      assignedClassIds: ['c1', 'c2', 'c3'],
      assignedSubjectIds: ['s1', 's2', 's8'],
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      is_active: true,
      first_login: false,
    },
    {
      id: 't2',
      user_id: 'u3',
      personnel_code: 'T-98103',
      national_id: '3333333333',
      username: '3333333333',
      first_name: 'استاد علیرضا',
      last_name: 'اکبری',
      specialty: 'فیزیک و آزمایشگاه',
      degree: 'کارشناسی ارشد فیزیک حالت جامد',
      phone: '09123333333',
      email: 'a.akbari@padideh.sch.ir',
      bio: 'مدرس فیزیک کنکور و طراح آزمون‌های آزمایشی کشوری با ۱۵ سال سابقه تدریس تخصصی.',
      assignedClassIds: ['c1', 'c2'],
      assignedSubjectIds: ['s3'],
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      is_active: true,
      first_login: false,
    },
    {
      id: 't3',
      user_id: 'u4',
      personnel_code: 'T-98104',
      national_id: '4444444444',
      username: '4444444444',
      first_name: 'استاد رضا',
      last_name: 'محمدی',
      specialty: 'شیمی و علوم آزمایشگاهی',
      degree: 'کارشناسی ارشد شیمی آلی',
      phone: '09124444444',
      email: 'r.mohammadi@padideh.sch.ir',
      bio: 'سرگروه آموزشی شیمی منطقه و مسئول آزمایشگاه تخصصی شیمی دبیرستان.',
      assignedClassIds: ['c1', 'c3'],
      assignedSubjectIds: ['s4'],
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      is_active: true,
      first_login: false,
    },
    {
      id: 't4',
      user_id: 'u5',
      personnel_code: 'T-98105',
      national_id: '5555555555',
      username: '5555555555',
      first_name: 'دکتر حسین',
      last_name: 'صادقی',
      specialty: 'ادبیات فارسی و نگارش',
      degree: 'دکتری زبان و ادبیات فارسی',
      phone: '09125555555',
      email: 'h.sadeghi@padideh.sch.ir',
      bio: 'پژوهشگر ادبیات معاصر و مدرس دوره‌های شاهنامه‌پژوهی و آیین نگارش.',
      assignedClassIds: ['c1', 'c2', 'c3', 'c4'],
      assignedSubjectIds: ['s5'],
      avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      is_active: true,
      first_login: false,
    },
  ],
  students: [
    {
      id: 'st1',
      user_id: 'u6',
      student_code: 'ST-1404101',
      national_id: '0011223344',
      first_name: 'امیررضا',
      last_name: 'رضایی',
      father_name: 'علیرضا',
      birth_date: '1388/04/15',
      class_id: 'c1',
      grade_level: 'tenth',
      field_of_study: 'علوم تجربی',
      parent_phone: '09121112233',
      address: 'تهران، زعفرانیه، خیابان اعجازی، پلاک ۱۸',
      discipline_score: 20,
      is_active: true,
      first_login: false,
      avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'st2',
      user_id: 'u7',
      student_code: 'ST-1404102',
      national_id: '0022334455',
      first_name: 'محمدحسین',
      last_name: 'صادقی',
      father_name: 'محمود',
      birth_date: '1388/06/20',
      class_id: 'c1',
      grade_level: 'tenth',
      field_of_study: 'علوم تجربی',
      parent_phone: '09122223344',
      address: 'تهران، میرداماد، میدان مادر، کوچه گلستان، پلاک ۵',
      discipline_score: 19.5,
      is_active: true,
      first_login: false,
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'st3',
      user_id: 'u8',
      student_code: 'ST-1404103',
      national_id: '0033445566',
      first_name: 'پارسا',
      last_name: 'کریمی',
      father_name: 'حسین',
      birth_date: '1388/02/10',
      class_id: 'c1',
      grade_level: 'tenth',
      field_of_study: 'علوم تجربی',
      parent_phone: '09123334455',
      address: 'تهران، پاسداران، بوستان ششم، پلاک ۲۲',
      discipline_score: 20,
      is_active: true,
      first_login: false,
      avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'st4',
      user_id: 'u9',
      student_code: 'ST-1404104',
      national_id: '0044556677',
      first_name: 'علی',
      last_name: 'موسوی',
      father_name: 'سید رضا',
      birth_date: '1388/09/12',
      class_id: 'c1',
      grade_level: 'tenth',
      field_of_study: 'علوم تجربی',
      parent_phone: '09124445566',
      address: 'تهران، قلهک، خیابان یخچال، پلاک ۴۰',
      discipline_score: 18.5,
      is_active: true,
      first_login: false,
      avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'st5',
      user_id: 'u10',
      student_code: 'ST-1404105',
      national_id: '0055667788',
      first_name: 'سینا',
      last_name: 'حیدری',
      father_name: 'کامران',
      birth_date: '1388/05/28',
      class_id: 'c1',
      grade_level: 'tenth',
      field_of_study: 'علوم تجربی',
      parent_phone: '09125556677',
      address: 'تهران، تجریش، خیابان دربند، پلاک ۱۲',
      discipline_score: 20,
      is_active: true,
      first_login: false,
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'st6',
      user_id: 'u11',
      student_code: 'ST-1404201',
      national_id: '0066778899',
      first_name: 'کیان',
      last_name: 'کاظمی',
      father_name: 'بهزاد',
      birth_date: '1388/03/14',
      class_id: 'c2',
      grade_level: 'tenth',
      field_of_study: 'علوم تجربی',
      parent_phone: '09126667788',
      address: 'تهران، اختیاریه شمالی، پلاک ۵',
      discipline_score: 20,
      is_active: true,
      first_login: false,
    },
    {
      id: 'st7',
      user_id: 'u12',
      student_code: 'ST-1404202',
      national_id: '0077889900',
      first_name: 'آرتین',
      last_name: 'طاهری',
      father_name: 'فرشید',
      birth_date: '1388/07/04',
      class_id: 'c2',
      grade_level: 'tenth',
      field_of_study: 'علوم تجربی',
      parent_phone: '09127778899',
      address: 'تهران، سعادت‌آباد، علامه جنوبی، پلاک ۹',
      discipline_score: 19,
      is_active: true,
      first_login: false,
    },
    {
      id: 'st8',
      user_id: 'u13',
      student_code: 'ST-1404301',
      national_id: '0088990011',
      first_name: 'سهراب',
      last_name: 'احمدی',
      father_name: 'پرویز',
      birth_date: '1386/01/18',
      class_id: 'c3',
      grade_level: 'twelfth',
      field_of_study: 'ریاضی و فیزیک',
      parent_phone: '09128889900',
      address: 'تهران، ولنجک، خیابان سیزدهم، پلاک ۲',
      discipline_score: 20,
      is_active: true,
      first_login: false,
    },
  ],
  grades: [
    {
      id: 'g1',
      student_id: 'st1',
      teacher_id: 't1',
      subject_id: 's1',
      class_id: 'c1',
      score: 19.5,
      max_score: 20,
      grade_type: 'daily',
      month: 'آبان',
      date: '1404/08/12',
      academic_year_id: 'ay1',
      description: 'فعالیت در حل مسائل توان گویا و حضور فعال در کلاس',
      created_at: new Date().toISOString(),
    },
    {
      id: 'g2',
      student_id: 'st2',
      teacher_id: 't1',
      subject_id: 's1',
      class_id: 'c1',
      score: 18,
      max_score: 20,
      grade_type: 'daily',
      month: 'آبان',
      date: '1404/08/12',
      academic_year_id: 'ay1',
      description: 'آزمونک کلاسی فصل اول',
      created_at: new Date().toISOString(),
    },
    {
      id: 'g3',
      student_id: 'st3',
      teacher_id: 't1',
      subject_id: 's1',
      class_id: 'c1',
      score: 20,
      max_score: 20,
      grade_type: 'daily',
      month: 'آبان',
      date: '1404/08/12',
      academic_year_id: 'ay1',
      description: 'پاسخگویی به سوالات تشریحی پای تخته و تمرین‌های تکمیلی',
      created_at: new Date().toISOString(),
    },
    {
      id: 'g4',
      student_id: 'st1',
      teacher_id: 't1',
      subject_id: 's2',
      class_id: 'c1',
      score: 20,
      max_score: 20,
      grade_type: 'midterm',
      month: 'آبان',
      date: '1404/08/20',
      academic_year_id: 'ay1',
      description: 'آزمون میان‌ترم هندسه ۱ (قضیه تالس و تشابه)',
      created_at: new Date().toISOString(),
    },
  ],
  attendance: [
    { id: 'att1', student_id: 'st1', class_id: 'c1', date: '1404/08/15', status: 'present', note: '' },
    { id: 'att2', student_id: 'st2', class_id: 'c1', date: '1404/08/15', status: 'present', note: '' },
    { id: 'att3', student_id: 'st3', class_id: 'c1', date: '1404/08/15', status: 'present', note: '' },
    { id: 'att4', student_id: 'st4', class_id: 'c1', date: '1404/08/15', status: 'late', note: '۱۰ دقیقه تأخیر به دلیل ترافیک' },
    { id: 'att5', student_id: 'st5', class_id: 'c1', date: '1404/08/15', status: 'excused', note: 'مرخصی پزشکی با گواهی' },
  ],
  homeworks: [
    {
      id: 'hw1',
      class_id: 'c1',
      subject_id: 's1',
      teacher_id: 't1',
      title: 'حل تمرین‌های پایانی فصل اول ریاضی ۱ (صفحه ۲۴ تا ۲۸)',
      description: 'لطفاً تمامی مسائل مربوط به مجموعه‌ها و الگوها را با رسم نمودار و استدلال کامل در دفتر ریاضی حل نموده و تصویر صفحات را بارگذاری نمایید.',
      due_date: '۱۴۰۴/۰۸/۳۰',
      created_at: new Date().toISOString(),
    },
    {
      id: 'hw2',
      class_id: 'c1',
      subject_id: 's2',
      teacher_id: 't1',
      title: 'اثبات قضایای تشابه مثلث‌ها و رسم اشکال هندسی با پرگار',
      description: 'قضایای ۱ و ۲ صفحه ۴۲ کتاب هندسه را اثبات کرده و یک کاربرد عملی در محاسبه ارتفاع اجسام بنویسید.',
      due_date: '۱۴۰۴/۰۹/۰۵',
      created_at: new Date().toISOString(),
    },
  ],
  submissions: [
    {
      id: 'sub1',
      homework_id: 'hw1',
      student_id: 'st1',
      student_name: 'امیررضا رضایی',
      answer_text: 'استاد گرامی، تمرین‌ها به صورت کامل با راه‌حل تشریحی نوشته شد.',
      file_name: 'math_hw_rezaei.pdf',
      file_type: 'pdf',
      submitted_at: new Date().toISOString(),
      grade: 20,
      teacher_feedback: 'بسیار دقیق و خوش‌خط، احسنت.',
      status: 'graded',
    },
    {
      id: 'sub2',
      homework_id: 'hw1',
      student_id: 'st2',
      student_name: 'محمدحسین صادقی',
      answer_text: 'مسائل شماره ۱ تا ۶ به همراه نمودار ون پیوست گردید.',
      file_name: 'homework_sadeghi.jpg',
      file_type: 'image',
      submitted_at: new Date().toISOString(),
      status: 'submitted',
    },
  ],
  announcements: [
    {
      id: 'an1',
      title: 'برگزاری المپیاد آزمایشی ریاضی و تجربی مرحله اول',
      content: 'به اطلاع کلیه دانش‌آموزان پایه‌های دهم و یازدهم می‌رساند، نخستین مرحله آزمون آزمایشی المپیادهای علمی روز پنج‌شنبه در سالن اجتماعات برگزار می‌گردد.',
      author_name: 'مدیریت آموزشگاه',
      author_role: 'admin',
      target: 'all',
      priority: 'high',
      created_at: new Date().toISOString(),
    },
    {
      id: 'an2',
      title: 'جلسه شورای دبیران پایه دهم جهت بررسی نمرات میان‌ترم',
      content: 'دبیران محترم پایه دهم روز دوشنبه ساعت ۱۳:۳۰ در اتاق کنفرانس حضور به هم رسانند.',
      author_name: 'معاونت آموزشی',
      author_role: 'admin',
      target: 'teachers',
      priority: 'normal',
      created_at: new Date().toISOString(),
    },
  ],
  reportCards: [],
  teacherNotes: [
    {
      id: 'tn1',
      student_id: 'st1',
      student_name: 'امیررضا رضایی',
      teacher_id: 't1',
      teacher_name: 'دکتر احمد حسینی',
      type: 'encouragement',
      title: 'پیشرفت چشمگیر در حل مسائل خلاقانه هندسه',
      content: 'دانش‌آموز دارای استعداد و درک فضایی بسیار بالا در هندسه تحلیلی است و پیشنهاد حضور در کلاس‌های آمادگی المپیاد داده می‌شود.',
      date: '1404/08/10',
      is_private_to_admin: false,
      created_at: new Date().toISOString(),
    },
  ],
  auditLogs: [
    {
      id: 'al1',
      user_id: 'u2',
      user_name: 'دکتر احمد حسینی',
      user_role: 'teacher',
      action: 'ثبت نمره مستمر',
      entity_type: 'grade',
      entity_id: 'g1',
      details: 'ثبت نمره ۱۹.۵ برای دانش‌آموز امیررضا رضایی در درس ریاضی ۱',
      timestamp: new Date().toISOString(),
      ip_address: '127.0.0.1',
    },
  ],
  schedules: [
    // Teacher Dr. Hosseini (t1) Schedule:
    {
      id: 'sch1',
      day_of_week_num: 0,
      day_name: 'شنبه',
      period_number: 1,
      start_time: '08:00',
      end_time: '09:20',
      school_class_id: 'c1',
      subject_id: 's1',
      teacher_id: 't1',
      room_number: '۱۰۱',
    },
    {
      id: 'sch2',
      day_of_week_num: 0,
      day_name: 'شنبه',
      period_number: 2,
      start_time: '09:35',
      end_time: '10:55',
      school_class_id: 'c2',
      subject_id: 's1',
      teacher_id: 't1',
      room_number: '۱۰۲',
    },
    {
      id: 'sch3',
      day_of_week_num: 1,
      day_name: 'یکشنبه',
      period_number: 1,
      start_time: '08:00',
      end_time: '09:20',
      school_class_id: 'c3',
      subject_id: 's8',
      teacher_id: 't1',
      room_number: '۲۰۱',
    },
    {
      id: 'sch4',
      day_of_week_num: 1,
      day_name: 'یکشنبه',
      period_number: 3,
      start_time: '11:10',
      end_time: '12:30',
      school_class_id: 'c1',
      subject_id: 's2',
      teacher_id: 't1',
      room_number: '۱۰۱',
    },
    {
      id: 'sch5',
      day_of_week_num: 2,
      day_name: 'دوشنبه',
      period_number: 2,
      start_time: '09:35',
      end_time: '10:55',
      school_class_id: 'c2',
      subject_id: 's2',
      teacher_id: 't1',
      room_number: '۱۰۲',
    },
    {
      id: 'sch6',
      day_of_week_num: 3,
      day_name: 'سه‌شنبه',
      period_number: 1,
      start_time: '08:00',
      end_time: '09:20',
      school_class_id: 'c1',
      subject_id: 's1',
      teacher_id: 't1',
      room_number: '۱۰۱',
    },
    {
      id: 'sch7',
      day_of_week_num: 4,
      day_name: 'چهارشنبه',
      period_number: 2,
      start_time: '09:35',
      end_time: '10:55',
      school_class_id: 'c3',
      subject_id: 's8',
      teacher_id: 't1',
      room_number: '۲۰۱',
    },
  ],
  users: [
    {
      id: 'u1',
      username: '1111111111',
      password: 'password',
      role: 'admin',
      first_name: 'دکتر محمد',
      last_name: 'رضایی',
      phone: '09121111111',
      email: 'admin@padideh.sch.ir',
      is_active: true,
      first_login: false,
    },
    {
      id: 'u2',
      username: '2222222222',
      password: 'password',
      role: 'teacher',
      teacher_id: 't1',
      first_name: 'دکتر احمد',
      last_name: 'حسینی',
      phone: '09122222222',
      email: 'dr.hosseini@padideh.sch.ir',
      is_active: true,
      first_login: false,
    },
    {
      id: 'u3',
      username: '3333333333',
      password: 'password',
      role: 'teacher',
      teacher_id: 't2',
      first_name: 'استاد علیرضا',
      last_name: 'اکبری',
      phone: '09123333333',
      email: 'a.akbari@padideh.sch.ir',
      is_active: true,
      first_login: false,
    },
    {
      id: 'u6',
      username: '0011223344',
      password: 'password',
      role: 'student',
      student_id: 'st1',
      first_name: 'امیررضا',
      last_name: 'رضایی',
      phone: '09121112233',
      is_active: true,
      first_login: false,
    },
  ],
};

class DatabaseStore {
  private data: DatabaseSchema;

  constructor() {
    this.data = this.load();
  }

  private load(): DatabaseSchema {
    try {
      if (fs.existsSync(DB_FILE)) {
        const raw = fs.readFileSync(DB_FILE, 'utf-8');
        return JSON.parse(raw);
      }
    } catch (e) {
      console.warn('Could not read persistent DB file, using initial data:', e);
    }
    this.save(INITIAL_DB);
    return JSON.parse(JSON.stringify(INITIAL_DB));
  }

  private save(dataToSave: DatabaseSchema) {
    try {
      fs.writeFileSync(DB_FILE, JSON.stringify(dataToSave, null, 2), 'utf-8');
    } catch (e) {
      console.error('Failed to write persistent DB file:', e);
    }
  }

  public get(): DatabaseSchema {
    return this.data;
  }

  public set(updater: (current: DatabaseSchema) => void) {
    updater(this.data);
    this.save(this.data);
  }

  public reset() {
    this.data = JSON.parse(JSON.stringify(INITIAL_DB));
    this.save(this.data);
  }
}

export const dbStore = new DatabaseStore();
